# Generated by Django 6.0.5 on 2026-06-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=30),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/back_ids/'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/front_ids/'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfies/'),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
