# Generated by Django 6.0.5 on 2026-06-03 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycdocument_id_number_kycprofile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='kyc.kycdocument')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='kyc.kycprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
