# Generated by Django 6.0.5 on 2026-06-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_kycapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url_name', models.CharField(help_text="Django URL name (e.g., 'user_management')", max_length=100)),
                ('icon', models.CharField(choices=[('verified_user', 'Verified User'), ('analytics', 'Analytics'), ('settings', 'Settings'), ('people', 'People'), ('description', 'Description'), ('security', 'Security'), ('assessment', 'Assessment'), ('dashboard', 'Dashboard'), ('document_scanner', 'Document Scanner'), ('history', 'History'), ('tune', 'Tune')], default='description', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order on dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
